In [1]:
import torch
from torch import nn
import random
from transformers import AutoConfig, AutoModel, AutoTokenizer
from torch import cdist as coss
from transformers import AutoTokenizer, DebertaV2ForSequenceClassification, AutoModelForSequenceClassification
# from torch.nn.functional import cosine_similarity as coss

# # model_name = 'bert-base-uncased'
# model_name = 'microsoft/deberta-v3-base'
# # model_name = 'm3rg-iitd/matscibert'
model_name = './../model_saved/checkpoint-140000'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

NOTE: Redirects are currently not supported in Windows or MacOs.
Some weights of the model checkpoint at ./../model_saved/checkpoint-140000 were not used when initializing DebertaV2Model: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing DebertaV2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaV2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [3]:
tokenizer.tokenize("The ingots were homogenized at 1250 °C for 2 h, then hot rolled to a final thickness of 4 mm through 7 passes.")

['▁The',
 '▁ingots',
 '▁were',
 '▁',
 'homogenized',
 '▁at',
 '▁1250',
 '▁°C',
 '▁for',
 '▁2',
 '▁',
 'h',
 ',',
 '▁the',
 'n',
 '▁hot',
 '▁rolled',
 '▁to',
 '▁',
 'a',
 '▁final',
 '▁thickness',
 '▁of',
 '▁4',
 '▁mm',
 '▁through',
 '▁7',
 '▁passes',
 '.']

In [10]:
m = nn.MaxPool1d(3)
a = torch.rand((32, 3, 512))
print(type(a), a.shape)

<class 'torch.Tensor'> torch.Size([32, 3, 512])


In [20]:
if isinstance(a, torch.Tensor):
    print('hello')

hello


In [21]:
np.array([1,2,3]).tolist()

[1, 2, 3]

In [32]:
import numpy as np
import pandas as pd

y_train = np.array([1,2,3,8,9,5,5])
y_train_preds = np.array([1,2,3,8,9,5,5])

y_val = np.array([1,2,3,4])
y_val_preds = np.array([1,2,3,4])

plot_best_text_y = np.array([1,2,3,4])
plot_best_text_preds = np.array([1,2,3,4])

plot_best_exp_y = np.array([1,2,3,4])
plot_best_exp_preds = np.array([1,2,3,4])

y_train = y_train.tolist()
y_train_preds = y_train_preds.tolist()

y_val = y_val.tolist()
y_val_preds = y_val_preds.tolist()

plot_best_text_y = plot_best_text_y.tolist()
plot_best_text_preds = plot_best_text_preds.tolist()

plot_best_exp_y = plot_best_exp_y.tolist()
plot_best_exp_preds = plot_best_exp_preds.tolist()

max_len = len(y_train)

y_val = y_val + [6666.0 for i in range(max_len-len(y_val))]
y_val_preds = y_val_preds + [6666.0 for i in range(max_len-len(y_val_preds))]
plot_best_text_y = plot_best_text_y + [6666.0 for i in range(max_len-len(plot_best_text_y))]
plot_best_text_preds = plot_best_text_preds + [6666.0 for i in range(max_len-len(plot_best_text_preds))]
plot_best_exp_y = plot_best_exp_y + [6666.0 for i in range(max_len-len(plot_best_exp_y))]
plot_best_exp_preds = plot_best_exp_preds + [6666.0 for i in range(max_len-len(plot_best_exp_preds))]

plot_result = pd.DataFrame({
    'y_train':y_train,
    'y_train_preds':y_train_preds,
    'y_val':y_val,
    'y_val_preds':y_val_preds,
    'plot_best_text_y':plot_best_text_y,
    'text_preds':plot_best_text_preds,
    'exp_y':plot_best_exp_y,
    'exp_preds':plot_best_exp_preds
})

plot_result.to_excel(f"./test_preds.xlsx", index=None)

In [28]:
len(y_train)

3

In [31]:
pd.DataFrame({
    'y_train':y_train,
    'y_train_preds':y_train_preds,
    'y_val':y_val,
    'y_val_preds':y_val_preds,
    'plot_best_text_y':plot_best_text_y,
    'text_preds':plot_best_text_preds,
    'exp_y':plot_best_exp_y,
    'exp_preds':plot_best_exp_preds
})

y_train  y_train_preds   y_val  y_val_preds  plot_best_text_y  text_preds  \
0        1              1     1.0          1.0               1.0         1.0   
1        2              2     2.0          2.0               2.0         2.0   
2        3              3     3.0          3.0               3.0         3.0   
3        8              8     4.0          4.0               4.0         4.0   
4        9              9  6666.0       6666.0            6666.0      6666.0   
5        5              5  6666.0       6666.0            6666.0      6666.0   
6        5              5  6666.0       6666.0            6666.0      6666.0   

    exp_y  exp_preds  
0     1.0        1.0  
1     2.0        2.0  
2     3.0        3.0  
3     4.0        4.0  
4  6666.0     6666.0  
5  6666.0     6666.0  
6  6666.0     6666.0

In [ ]:
plot_best_text_y = plot_best_text_y.tolist()
plot_best_text_preds = plot_best_text_preds.tolist()

plot_best_exp_y = plot_best_exp_y.tolist()
plot_best_exp_preds = plot_best_exp_preds.tolist()

In [9]:
m(a)

tensor([[[0.5959, 0.8860, 0.7837,  ..., 0.8707, 0.9053, 0.4169],
         [0.9552, 0.9554, 0.6312,  ..., 0.5201, 0.7477, 0.7594],
         [0.8800, 0.6271, 0.6936,  ..., 0.6894, 0.9080, 0.9062]],

        [[0.7379, 0.9612, 0.5960,  ..., 0.8998, 0.6183, 0.9217],
         [0.1391, 0.4892, 0.8807,  ..., 0.9717, 0.7012, 0.8975],
         [0.9542, 0.3861, 0.7734,  ..., 0.9592, 0.7206, 0.4143]],

        [[0.7508, 0.9231, 0.9984,  ..., 0.9767, 0.5142, 0.8203],
         [0.9102, 0.9985, 0.7425,  ..., 0.4172, 0.3093, 0.5437],
         [0.4984, 0.9878, 0.6646,  ..., 0.8639, 0.9838, 0.9096]],

        ...,

        [[0.5103, 0.9707, 0.9005,  ..., 0.6180, 0.8478, 0.9414],
         [0.5684, 0.9760, 0.9744,  ..., 0.8820, 0.9478, 0.3601],
         [0.9295, 0.7246, 0.6838,  ..., 0.8547, 0.6498, 0.6249]],

        [[0.9236, 0.7588, 0.7937,  ..., 0.3060, 0.7578, 0.9948],
         [0.7690, 0.7608, 0.9139,  ..., 0.7017, 0.9740, 0.5370],
         [0.8955, 0.9404, 0.4806,  ..., 0.4686, 0.6223, 0.9150]],

 

In [17]:
a = b = c = torch.rand((3, 7)).unsqueeze(1)
torch.concat([a, b,c ], dim=1).shape

torch.Size([3, 3, 7])

In [2]:
# from torch.nn.utils.rnn import pad_sequence
# a = torch.rand(3, 3)
# b = torch.rand(2, 3)
# c = torch.rand(1, 3)
# pad_sequence([a, b, c]).size()

In [3]:
def set_global_seed(seed=123):
    # for Tensorflow
    try:
        import tensorflow as tf
    except ImportError:
        pass
    else:
        tf.random.set_seed(seed)
        tf.experimental.numpy.random.seed(seed)
        tf.set_random_seed(seed)
        # When running on the CuDNN backend, two further options must be set
        os.environ['TF_CUDNN_DETERMINISTIC'] = '1'
        os.environ['TF_DETERMINISTIC_OPS'] = '1'

    # for PyTorch
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    # When running on the CuDNN backend, two further options must be set
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    # Set a fixed value for the hash seed
    os.environ["PYTHONHASHSEED"] = str(seed)

In [4]:
ids = [1,2,3,4,5,6,7,8,9]
random.seed(0)
for i in range(2):
    random.shuffle(ids)
    print(ids)

[8, 6, 2, 4, 5, 3, 1, 9, 7]
[2, 8, 4, 7, 1, 6, 5, 3, 9]


In [ ]:
[8, 6, 2, 4, 5, 3, 1, 9, 7]
[2, 8, 4, 7, 1, 6, 5, 3, 9]


In [8]:
a

tensor([[0.5968, 0.4643, 0.0421],
        [0.9798, 0.1801, 0.5089],
        [0.4546, 0.3708, 0.7303]])

In [9]:
b

tensor([[0.4655, 0.1563, 0.3816],
        [0.0399, 0.7582, 0.1021]])

In [10]:
c

tensor([[0.1049, 0.0707, 0.9922]])

In [11]:
pad_sequence([a, b, c])

tensor([[[0.5968, 0.4643, 0.0421],
         [0.4655, 0.1563, 0.3816],
         [0.1049, 0.0707, 0.9922]],

        [[0.9798, 0.1801, 0.5089],
         [0.0399, 0.7582, 0.1021],
         [0.0000, 0.0000, 0.0000]],

        [[0.4546, 0.3708, 0.7303],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]]])

In [49]:
# model_name = 'bert-base-uncased'
# model_name = 'microsoft/deberta-v3-base'
# model_name = 'm3rg-iitd/matscibert'
model_name = './../model_saved/checkpoint-140000'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# for name, param in model.named_parameters():
#     # print(type(name), name)
#     if 'pooler' in name:
#         print('hello')
#         break

Some weights of the model checkpoint at ./../model_saved/checkpoint-140000 were not used when initializing DebertaV2Model: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing DebertaV2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaV2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [50]:
def get_embeddings(text):
    encoded_input = tokenizer(text, padding=True, truncation=False, return_tensors="pt")
    model_output = model(**encoded_input)
    if 'pooler_output' in model_output.keys():
        return model_output['pooler_output']
    else:
        return model_output['last_hidden_state']

In [52]:
text = 'The experimental steel was melted in vacuum induction melting furnace at first, and then hot-forged. After Some small plates were cut from the as-received hot forged plate, and then solution-treated at 1050 °C for 4 h. The solution-treated specimen was cold rolled to a thickness reduction of 57%. The the cold rolled specimen was performed by tempering at temperature of 590 °C for 60 min, followed by air cooling to room temperature.'
len(tokenizer.tokenize(text, add_special_tokens=True))

89

In [45]:
text1 = "The sample was heated at 150–400 °C"
text2 = "The steel was heated at 150–400 °C"

text1 = " The sample was heated at 150–400 °C"
text2 = "The sample was heated at 150–400 °C "


print(tokenizer.tokenize(text1, add_special_tokens=True))
print(tokenizer.tokenize(text2, add_special_tokens=True))

# output1, output2 = get_embeddings(text1), get_embeddings(text2)
# print(output1.shape, output2.shape)

['[CLS]', '▁The', '▁sample', '▁was', '▁heated', '▁at', '▁150', '–', '400', '▁°', 'C', '[SEP]']
['[CLS]', '▁The', '▁sample', '▁was', '▁heated', '▁at', '▁150', '–', '400', '▁°', 'C', '[SEP]']


In [39]:
text2 = "Mn"
print(tokenizer.tokenize(text2, add_special_tokens=True))

['[CLS]', '▁Mn', '[SEP]']


In [17]:
text = 'I 150–400 °C MPa'
text = 'M 150–400 °C MPa'

encoded_input = tokenizer(text, padding=True, truncation=False, return_tensors="pt")
model_output = model(**encoded_input)
model_output['last_hidden_state'].shape

torch.Size([1, 9, 768])

In [4]:
# def get_embeddings(text):
#     encoded_input = tokenizer(
#         text_list, padding=True, truncation=True, return_tensors="tf"
#     )
#     encoded_input = {k: v for k, v in encoded_input.items()}
#     model_output = model(**encoded_input)
#     return cls_pooling(model_output)

def get_embeddings(text):
    encoded_input = tokenizer(text, padding=True, truncation=False, return_tensors="pt")
    model_output = model(**encoded_input)
    if 'pooler_output' in model_output.keys():
        return model_output['pooler_output']
    else:
        return model_output['last_hidden_state'][:,0]

def cos_sim(string1, string2):
    with torch.no_grad():    
        output = coss(get_embeddings(string1), get_embeddings(string2))
    return output[0]

In [19]:
a = get_embeddings('10') - get_embeddings('20')
b = get_embeddings('200')
coss(a,b)

tensor([[26.2110]], grad_fn=<CdistBackward0>)

In [20]:
a = get_embeddings('800') - get_embeddings('600')
b = get_embeddings('200')
coss(a,b)

tensor([[27.4844]], grad_fn=<CdistBackward0>)

In [30]:
cos_sim('100', '200')

tensor([0.4510])

In [31]:
cos_sim('400', '300')

tensor([0.1677])

In [23]:
for i in range(100, 1000, 100):
    print(cos_sim(str(i), str(i-20)))

tensor([12.5964])
tensor([13.4804])
tensor([12.5896])
tensor([13.5851])
tensor([15.8004])
tensor([13.7600])
tensor([14.0959])
tensor([15.1334])
tensor([15.9370])


In [ ]:
from sklearn.decomposition import PCA

def dr_pca(data, n_components=2, seed=666):
    u = PCA(n_components=n_components, random_state=seed).fit_transform(data)
    return u

In [16]:
print(cos_sim('1400', '1600'))
print(cos_sim('1000', '1200'))

tensor([12.6399])
tensor([11.7883])


In [14]:
print(cos_sim('1100', '1300'))
print(cos_sim('800', '600'))

tensor([11.8488])
tensor([10.9926])


In [13]:
print(cos_sim('500', '300'))
print(cos_sim('900', '700'))

tensor([10.8315])
tensor([10.7940])


In [8]:
a = get_embeddings('600') - get_embeddings('400')
b = get_embeddings('500') - get_embeddings('300')
coss(a,b)

tensor([[15.1015]], grad_fn=<CdistBackward0>)

In [6]:
print(cos_sim('10000', '12000'))
print(cos_sim('1000', '1200'))
print(cos_sim('100', '120'))

tensor([11.7146])
tensor([11.2823])
tensor([14.4995])


In [7]:
print(cos_sim('Female', 'male'))
print(cos_sim('King', 'Queen'))

tensor([16.9365])
tensor([18.8416])


In [8]:
print(cos_sim('Fe', 'Iron'))
print(cos_sim('O', 'Oxgen'))

tensor([18.5271])
tensor([19.5418])


In [295]:
# text = '1234464616'
# encoded_input = tokenizer(text, padding=True, truncation=True, return_tensors="pt")
# pooled = model(**encoded_input)
# # model_output['last_hidden_state'][:,0].shape

In [296]:
# 'pooler_output' in pooled.keys()

In [297]:
# get_embeddings('ferromagnetic')-get_embeddings('NiFe')+get_embeddings('IrMn')-get_embeddings('antiferromagnetic')

In [9]:
coss(get_embeddings('ferromagnetic')-get_embeddings('NiFe')+get_embeddings('IrMn'),get_embeddings('antiferromagnetic')) 

tensor([[17.6811]], grad_fn=<CdistBackward0>)

In [299]:
# Zr − ZrO2 ≈ Cr − Cr2O3 ≈ Ni − NiO) and ‘structure of ’ (Zr − HCP ≈ Cr − BCC ≈ Ni − FCC)